import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/shared/components/ThemeProvider";
import NavbarClient from "@/shared/components/navbarClient";
import SmoothScroll from "@/shared/components/SmoothLenis";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable}  h-full antialiased`} 
    suppressHydrationWarning>
      <body className={`  min-h-full flex flex-col`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          {/* <NavbarClient /> */}
          <SmoothScroll>

          {children}
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
